### PR TITLE
Fixed the position of the stop button

### PR DESCRIPTION
**Pull request by aishwarya-mali**
### Issue Link 
* #15 

### Description
* The stop button is positioned in the same element where the received messages are shown so set its position so it won't bounce as the content changes.

### Changes
* added styles to fix the position of the stop button.

### Video of issue resolved
[stop-button.webm](https://github.com/seonwoo960000/ai-sidebar/assets/43086476/78589a95-3c74-4d1e-a152-0beacfeb43ae)

### CODE REVIEW

**Comment by aishwarya-mali** [comment]
@seonwoo960000 Please check. I've added a video now.

**Comment by seonwoo960000** [comment]
@aishwarya-mali Thank you for the detailed video. I've checked that it's working perfectly! 
By the way, I wonder how added css make it work 🤔 

```css
.chat-message-buttons {
  position: absolute;
  bottom: 220px;
  left: 50%;
}
```

**Comment by seonwoo960000** [comment]
@all-contributors bot please add @aishwarya-mali for UI/UX

**Review by seonwoo960000 — APPROVED** [review]

**Comment by seonwoo960000** [comment]
@all-contributors bot please add @aishwarya-mali for design

**Comment by seonwoo960000** [comment]
@aishwarya-mali , thank you for the first contribution. Hope to make better software with you 👍

**Comment by aishwarya-mali** [comment]
> @aishwarya-mali Thank you for the detailed video. I've checked that it's working perfectly! By the way, I wonder how added css make it work 🤔
> 
> ```css
> .chat-message-buttons {
>   position: absolute;
>   bottom: 220px;
>   left: 50%;
> }
> ```

the section of input had a height of 210px in grid and positioned stop button according to that.

**Comment by seonwoo960000** [comment]
Oh wow, thank you for the explanation. I think it's better to add some comments on it. I'll add it.

**Pull request merged**
